import type { CheatSheet } from '@/types';

export const cheatSheets: CheatSheet[] = [
  {
    id: '1',
    title: 'Essential Linux Commands',
    category: 'Linux',
    items: [
      { command: 'ls -la', description: 'List all files including hidden with details' },
      { command: 'cd -', description: 'Go to previous directory' },
      { command: 'pwd', description: 'Print working directory' },
      { command: 'mkdir -p path/to/dir', description: 'Create directory and parents' },
      { command: 'rm -rf directory', description: 'Force remove directory recursively' },
      { command: 'cp -r src dest', description: 'Copy directory recursively' },
      { command: 'mv old new', description: 'Rename or move file/directory' },
      { command: 'chmod +x file', description: 'Make file executable' },
      { command: 'chown user:group file', description: 'Change file ownership' },
      { command: 'grep -r "pattern" .', description: 'Search recursively for pattern' },
      { command: 'find . -name "*.log"', description: 'Find files by name pattern' },
      { command: 'tail -f logfile.log', description: 'Follow log file in real-time' },
      { command: 'ps aux | grep process', description: 'Find running process' },
      { command: 'kill -9 PID', description: 'Force kill process by ID' },
      { command: 'df -h', description: 'Show disk space usage' },
      { command: 'du -sh *', description: 'Show directory sizes' },
      { command: 'free -h', description: 'Show memory usage' },
      { command: 'top', description: 'Interactive process viewer' },
      { command: 'ssh user@host', description: 'Connect to remote server' },
      { command: 'scp file user@host:/path', description: 'Secure copy to remote' },
      { command: 'tar -xzf archive.tar.gz', description: 'Extract tar.gz archive' },
      { command: 'curl -O https://url/file', description: 'Download file from URL' },
      { command: 'wget https://url/file', description: 'Download file (alternative)' },
    ],
    tags: ['linux', 'cli', 'bash', 'terminal'],
  },
  {
    id: '2',
    title: 'Git Essential Commands',
    category: 'Git',
    items: [
      { command: 'git init', description: 'Initialize new Git repository' },
      { command: 'git clone <url>', description: 'Clone remote repository' },
      { command: 'git status', description: 'Show working tree status' },
      { command: 'git add .', description: 'Stage all changes' },
      { command: 'git commit -m "message"', description: 'Commit staged changes' },
      { command: 'git push origin main', description: 'Push to remote main branch' },
      { command: 'git pull', description: 'Fetch and merge remote changes' },
      { command: 'git branch', description: 'List local branches' },
      { command: 'git branch -a', description: 'List all branches (local + remote)' },
      { command: 'git checkout -b feature', description: 'Create and switch to new branch' },
      { command: 'git switch branch-name', description: 'Switch to existing branch' },
      { command: 'git merge branch-name', description: 'Merge branch into current' },
      { command: 'git rebase main', description: 'Rebase current branch onto main' },
      { command: 'git rebase -i HEAD~3', description: 'Interactive rebase last 3 commits' },
      { command: 'git stash', description: 'Stash current changes' },
      { command: 'git stash pop', description: 'Apply and remove stashed changes' },
      { command: 'git log --oneline', description: 'Compact commit history' },
      { command: 'git log --graph --all', description: 'Visual branch history' },
      { command: 'git diff', description: 'Show unstaged changes' },
      { command: 'git diff --staged', description: 'Show staged changes' },
      { command: 'git reset --hard HEAD', description: 'Discard all local changes' },
      { command: 'git revert HEAD', description: 'Undo last commit safely' },
      { command: 'git remote -v', description: 'Show remote URLs' },
      { command: 'git fetch --prune', description: 'Clean up stale remote refs' },
      { command: 'git reflog', description: 'View reference history (recovery)' },
    ],
    tags: ['git', 'version-control', 'cli'],
  },
  {
    id: '3',
    title: 'Gradle Commands',
    category: 'Gradle',
    items: [
      { command: './gradlew build', description: 'Build project (compile, test, jar)' },
      { command: './gradlew clean', description: 'Delete build directory' },
      { command: './gradlew run', description: 'Run application' },
      { command: './gradlew test', description: 'Run tests' },
      { command: './gradlew dependencies', description: 'Show all dependencies' },
      { command: './gradlew :app:dependencies', description: 'Show dependencies for specific module' },
      { command: './gradlew tasks', description: 'List all available tasks' },
      { command: './gradlew tasks --all', description: 'List all tasks including hidden' },
      { command: './gradlew build --refresh-dependencies', description: 'Refresh dependency cache' },
      { command: './gradlew build --offline', description: 'Build without network access' },
      { command: './gradlew clean build', description: 'Clean and rebuild' },
      { command: './gradlew jar', description: 'Build JAR file only' },
      { command: './gradlew javadoc', description: 'Generate documentation' },
      { command: './gradlew projects', description: 'List all subprojects' },
      { command: './gradlew help --task taskName', description: 'Get help on specific task' },
      { command: './gradlew --daemon', description: 'Run with background daemon' },
      { command: './gradlew --no-daemon', description: 'Run without daemon' },
      { command: './gradlew --profile', description: 'Generate build profile report' },
      { command: './gradlew --dry-run', description: 'Show tasks without executing' },
      { command: './gradlew --continue', description: 'Continue after task failures' },
    ],
    tags: ['gradle', 'build', 'java', 'kotlin'],
  },
  {
    id: '4',
    title: 'React Patterns & Hooks',
    category: 'React',
    items: [
      { command: 'const [state, setState] = useState(initial)', description: 'Declare state variable' },
      { command: 'useEffect(() => { ... }, [deps])', description: 'Side effect with dependencies' },
      { command: 'useMemo(() => compute(), [deps])', description: 'Memoize computed value' },
      { command: 'useCallback(() => {}, [deps])', description: 'Memoize function reference' },
      { command: 'const ref = useRef(initial)', description: 'Create mutable ref' },
      { command: 'const { a, b } = useContext(MyContext)', description: 'Consume context value' },
      { command: 'const [state, dispatch] = useReducer(reducer, initial)', description: 'Complex state management' },
      { command: '<Component key={id} />', description: 'Force re-mount with key' },
      { command: '{condition && <Component />}', description: 'Conditional rendering' },
      { command: '{items.map(i => <Item key={i.id} />)}', description: 'List rendering' },
      { command: '...props', description: 'Spread props to child' },
      { command: 'children', description: 'Access nested content' },
      { command: 'React.memo(Component)', description: 'Prevent unnecessary re-renders' },
      { command: 'forwardRef((props, ref) => ...)', description: 'Forward ref to child' },
      { command: 'createPortal(child, container)', description: 'Render outside DOM hierarchy' },
      { command: 'Suspense fallback={<Loader>}>', description: 'Loading state for lazy components' },
      { command: 'lazy(() => import("./Module"))', description: 'Code splitting' },
    ],
    tags: ['react', 'hooks', 'patterns', 'frontend'],
  },
  {
    id: '5',
    title: 'Docker Essentials',
    category: 'Docker',
    items: [
      { command: 'docker build -t myapp .', description: 'Build image from Dockerfile' },
      { command: 'docker run -d -p 8080:80 myapp', description: 'Run container in background' },
      { command: 'docker ps', description: 'List running containers' },
      { command: 'docker ps -a', description: 'List all containers' },
      { command: 'docker images', description: 'List images' },
      { command: 'docker stop container', description: 'Stop running container' },
      { command: 'docker start container', description: 'Start stopped container' },
      { command: 'docker rm container', description: 'Remove container' },
      { command: 'docker rmi image', description: 'Remove image' },
      { command: 'docker logs container', description: 'View container logs' },
      { command: 'docker logs -f container', description: 'Follow logs in real-time' },
      { command: 'docker exec -it container bash', description: 'Enter running container' },
      { command: 'docker inspect container', description: 'View detailed container info' },
      { command: 'docker compose up -d', description: 'Start services in background' },
      { command: 'docker compose down', description: 'Stop and remove services' },
      { command: 'docker compose logs -f', description: 'Follow compose logs' },
      { command: 'docker system prune', description: 'Clean up unused resources' },
      { command: 'docker volume ls', description: 'List volumes' },
      { command: 'docker network ls', description: 'List networks' },
      { command: 'docker cp file container:/path', description: 'Copy file to container' },
    ],
    tags: ['docker', 'containers', 'devops', 'deployment'],
  },
];
