import type { Playbook } from '@/types';

export const playbooks: Playbook[] = [
  {
    id: '1',
    title: 'Gradle Build Fails with Dependency Resolution Error',
    symptoms: [
      'Build fails with "Could not resolve all dependencies"',
      'Error mentions configuration ":compileClasspath" or ":runtimeClasspath"',
      'Network timeout errors during dependency download',
      'Missing artifact errors',
    ],
    probableCauses: [
      'Repository not declared in build.gradle',
      'Incorrect dependency coordinates (group, name, version)',
      'Network connectivity issues',
      'Proxy configuration missing',
      'Corrupted Gradle cache',
    ],
    commands: [
      './gradlew build --refresh-dependencies',
      './gradlew dependencies --configuration compileClasspath',
      './gradlew clean build',
      'rm -rf ~/.gradle/caches/modules-2/files-2.1/*',
    ],
    solutions: [
      'Verify mavenCentral() or other repositories are declared in your build file',
      'Check dependency coordinates on Maven Central or the library\'s documentation',
      'If behind a proxy, configure gradle.properties with proxy settings',
      'Clear Gradle cache and rebuild',
      'Use a specific Gradle version compatible with your project',
    ],
    finalChecks: [
      'Run ./gradlew build to verify the build succeeds',
      'Check that all expected dependencies are resolved',
      'Verify the application runs correctly',
    ],
    relatedPages: [{ title: 'Getting Started with DevFlow Wiki', slug: 'guides/getting-started' }],
    tags: ['gradle', 'build', 'dependencies', 'java'],
  },
  {
    id: '2',
    title: 'JavaFX Application Does Not Start',
    symptoms: [
      'Application window does not appear',
      'Error: "JavaFX runtime components are missing"',
      'Empty window appears then closes immediately',
      'ClassNotFoundException for JavaFX classes',
    ],
    probableCauses: [
      'JavaFX not included in module path',
      'Using JRE instead of JDK',
      'Missing --module-path and --add-modules JVM arguments',
      'JavaFX version mismatch with Java version',
    ],
    commands: [
      'java --version',
      'javac --version',
      './gradlew run --info',
    ],
    solutions: [
      'Ensure you are using JDK 17 or later with JavaFX bundled, or add JavaFX SDK separately',
      'Add JavaFX dependencies to your build.gradle:',
      '  dependencies {',
      '      implementation "org.openjfx:javafx-controls:21"',
      '      implementation "org.openjfx:javafx-fxml:21"',
      '  }',
      'For modular projects, ensure module-info.java requires javafx.controls and other needed modules',
      'When running from IDE, configure VM options: --module-path /path/to/javafx/lib --add-modules javafx.controls,javafx.fxml',
    ],
    finalChecks: [
      'Application window appears with expected content',
      'No error messages in console',
      'UI controls are responsive',
    ],
    relatedPages: [],
    tags: ['javafx', 'startup', 'java', 'ui'],
  },
  {
    id: '3',
    title: 'Git Push Fails with Authentication Error',
    symptoms: [
      'Error: "Authentication failed"',
      'Error: "Permission denied (publickey)"',
      'Prompted for password but authentication still fails',
      'Error: "Could not read from remote repository"',
    ],
    probableCauses: [
      'SSH key not configured or not added to ssh-agent',
      'GitHub/GitLab SSH key not registered in account settings',
      'Using HTTPS URL but credentials not cached',
      'Two-factor authentication enabled without personal access token',
      'Wrong remote URL (HTTPS vs SSH)',
    ],
    commands: [
      'git remote -v',
      'cat ~/.ssh/id_ed25519.pub',
      'ssh-add -l',
      'ssh-add ~/.ssh/id_ed25519',
      'ssh -T git@github.com',
    ],
    solutions: [
      'Generate SSH key if not exists: ssh-keygen -t ed25519 -C "your@email.com"',
      'Add SSH key to GitHub/GitLab account settings',
      'Add key to ssh-agent: ssh-add ~/.ssh/id_ed25519',
      'If using HTTPS, switch to SSH: git remote set-url origin git@github.com:user/repo.git',
      'If 2FA is enabled, use a Personal Access Token instead of password',
      'Configure Git to use SSH: git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"',
    ],
    finalChecks: [
      'Test SSH connection: ssh -T git@github.com',
      'Try pushing again: git push',
      'Verify remote URL is correct: git remote -v',
    ],
    relatedPages: [],
    tags: ['git', 'authentication', 'ssh', 'push'],
  },
  {
    id: '4',
    title: 'React Component Not Re-rendering',
    symptoms: [
      'State changes but UI does not update',
      'Component appears frozen',
      'Console shows state change but screen unchanged',
      'useEffect not triggering as expected',
    ],
    probableCauses: [
      'Mutating state directly instead of creating new object',
      'Using incorrect dependency array in useEffect',
      'Component key not changing when it should',
      'Parent component not passing updated props',
      'Memoization preventing re-render (React.memo, useMemo)',
    ],
    commands: [
      '# Check React DevTools for component updates',
      '# Add console.log to trace state changes',
    ],
    solutions: [
      'Never mutate state directly. Use spread operator or immutable updates:',
      '  // Wrong: state.push(newItem)',
      '  // Correct: setState([...state, newItem])',
      'For objects: setState({ ...state, property: newValue })',
      'Check useEffect dependency array - include all values used in the effect',
      'Use React DevTools Profiler to identify re-render issues',
      'If using React.memo, verify props comparison is working correctly',
      'Consider using a key prop to force re-mount when needed',
    ],
    finalChecks: [
      'Component re-renders when state changes',
      'UI reflects the current state',
      'No console warnings about state updates',
    ],
    relatedPages: [{ title: 'React Hooks Guide', slug: 'react/hooks' }],
    tags: ['react', 'rendering', 'state', 'debugging'],
  },
  {
    id: '5',
    title: 'Docker Container Exits Immediately',
    symptoms: [
      'Container starts then stops within seconds',
      'docker ps does not show the container',
      'Exit code 0 or 1 shortly after start',
      'No output in container logs',
    ],
    probableCauses: [
      'Main process completes and exits',
      'CMD or ENTRYPOINT not specified correctly',
      'Application crashes on startup',
      'Missing environment variables or configuration',
      'Port already in use',
    ],
    commands: [
      'docker ps -a',
      'docker logs <container-id>',
      'docker inspect <container-id>',
      'docker run -it <image> /bin/bash',
    ],
    solutions: [
      'Check container logs: docker logs <container-id>',
      'Ensure your Dockerfile has a CMD or ENTRYPOINT that runs a foreground process',
      'Avoid running commands that complete immediately (use tail -f /dev/null for debug)',
      'Run interactively to debug: docker run -it <image> /bin/sh',
      'Verify environment variables are set correctly',
      'Check if required ports are available: docker run -p 3000:3000 <image>',
      'Review Dockerfile for syntax errors or missing steps',
    ],
    finalChecks: [
      'Container stays running: docker ps shows status "Up"',
      'Application is accessible on expected port',
      'Logs show successful startup messages',
    ],
    relatedPages: [],
    tags: ['docker', 'containers', 'debugging', 'devops'],
  },
];
